# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('recommended', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isStudent', models.BooleanField(default=True)),
                ('isParent', models.BooleanField(default=False)),
                ('isTeacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('cost', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('request', models.TextField(blank=True, max_length=1000)),
                ('report', models.TextField(blank=True, max_length=500)),
                ('feedback', models.TextField(blank=True, max_length=500)),
                ('paid', models.BooleanField(default=False)),
                ('completedTeacher', models.BooleanField(default=False)),
                ('completedStudent', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('changedForTeacher', models.BooleanField(default=True)),
                ('changedForStudent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='school.Profile')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='school.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='school.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Topics', to='school.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='learnedTopics',
            field=models.ManyToManyField(blank=True, related_name='SessionsLearned', to='school.Topic'),
        ),
        migrations.AddField(
            model_name='session',
            name='plannedTopics',
            field=models.ManyToManyField(blank=True, related_name='SessionsPlanned', to='school.Topic'),
        ),
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sessions', to='school.Student'),
        ),
        migrations.AddField(
            model_name='session',
            name='subjects',
            field=models.ManyToManyField(related_name='Sessions', to='school.Subject'),
        ),
        migrations.AddField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sessions', to='school.Profile'),
        ),
        migrations.AddField(
            model_name='session',
            name='unlearnedTopics',
            field=models.ManyToManyField(blank=True, related_name='SessionsFailed', to='school.Topic'),
        ),
    ]
