# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accountName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='sortCode',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
