# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170822_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='school.Profile'),
        ),
    ]
