# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
