# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_resource_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50)),
                ('sortCode', models.CharField(max_length=8)),
                ('accountNumber', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='accountName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='accountNumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sortCode',
        ),
        migrations.AlterField(
            model_name='session',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sessions', to='school.Teacher', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='school.Profile'),
        ),
    ]
