# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20170911_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Students', to='school.Teacher'),
            preserve_default=False,
        ),
    ]
