# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='uploads',
            field=models.ManyToManyField(related_name='Sessions', to='school.Upload'),
        ),
    ]
