# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_session_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
