# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalinfo', '0006_auto_20170218_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='higher',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='joint_discount',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nat5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skype_discount',
        ),
    ]
