# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
